### ISSUE TITLE
Issue with Devika not responding upon startup

### ISSUE THREAD

**Issue by gianfrancosaltarelli** [stitionai/devika#462]
Dear stitionai,

I hope this message finds you well. I am reaching out to you because I am experiencing an issue with the Devika application I am using, and I was wondering if you could provide assistance in resolving it.

The problem I am encountering is that when I start the Devika application, it does not respond, and I am unable to interact with it in any way. I have attempted several actions to try to troubleshoot, such as updating the UI dependencies and restarting the application, but the issue persists.

I wonder if you could help me identify the underlying cause of this problem and provide guidance on how to resolve it. If you need any further information, I would be happy to provide it.

I greatly appreciate your attention to this matter and any assistance you can provide in resolving it.

I look forward to your prompt response.

Best regards,
gianfranco saltarelli
![Screenshot 2024-04-18 205609](https://github.com/stitionai/devika/assets/159237259/43497e35-2fa8-4379-81cc-34beb5064f22)

**Comment by nickching** [comment]
I've encountered the same issue a couple of days ago. Devika worked the day before, but the next day, agent never response. I've tried switch between GPT and local Ollama, same result.
The similar case happened around the same time frame (ref. to issue #445 )  so I think maybe it's because incompatible issue with some latest updates of some modules.

**Comment by gianfrancosaltarelli** [comment]
Hello! I appreciate you reaching out and sharing your experience. I'll delve into investigating updates, recent changes, and troubleshooting the issue. Rest assured, I'll keep you updated if I make any progress or require additional information. Also, I'll be sure to monitor issue #445 as you suggested. Thank you once again for your valuable input.

**Comment by ARajgor** [comment]
> Hello! I appreciate you reaching out and sharing your experience. I'll delve into investigating updates, recent changes, and troubleshooting the issue. Rest assured, I'll keep you updated if I make any progress or require additional information. Also, I'll be sure to monitor issue #445 as you suggested. Thank you once again for your valuable input.

Share the the backend logs. Also do a clean install.

**Comment by drawat71** [comment]
same issue

**Comment by nickching** [comment]
Thanks for the response. I've done the clean installation several times and no change.
Here's the debug info from backend.
It's frozen here forever. 
Thanks

```(devika) $ python3 devika.py --debug
24.04.19 16:48:08: root: INFO   : Initializing Devika...
24.04.19 16:48:08: root: INFO   : Initializing Prerequisites Jobs...
24.04.19 16:48:09: root: INFO   : Loading sentence-transformer BERT models...
24.04.19 16:48:13: root: INFO   : BERT model loaded successfully.
24.04.19 16:48:14: root: INFO   : Ollama available
24.04.19 16:48:14: root: INFO   : Devika is up and running!
24.04.19 16:48:23: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'write a Python game of "snake"', 'timestamp': '2024-04-19 16:48:23'}}```

**Comment by ARajgor** [comment]
share the config.

**Comment by ARajgor** [comment]
I meant to be this, sorry

```
- OS: [e.g. Windows, Linux, MacOS]
- Python version: [e.g. 3.10]
- Node version: [e.g. 18.0.0]
- bun version: [e.g. 0.1.0]
- search engine: [e.g. google]
- Model: [e.g. gpt, cluade]
```

**Comment by xylozd** [comment]
Same issue ,..!! kindly resolve it.. 

```
OS : Windows 11
Python 3.11.2
Node v20.12.2
Bun v1.1.4
search engine : Google 
Model : gpt 3.5 , cluade all
```

**Comment by moonjieun** [comment]
Same issue ,..!! kindly resolve it..
me too

**Comment by patpatwithhat** [comment]
Had the same problem a couple of days ago.

**Comment by ARajgor** [comment]
can you all share the browser console log after the sending first message? create a new project, and select the model. share the console log of the browser and and python terminal.

**Comment by maikmetzger** [comment]
same problem

**Comment by start-life** [comment]
24.04.21 14:49:54: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 27341}
Invalid response from the model, trying again...
24.04.21 14:49:54: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 29034}
Model: llama3:latest, Enum: OLLAMA
24.04.21 14:50:04: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 28860}
Invalid response from the model, trying again...
24.04.21 14:50:05: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 30459}
Model: llama3:latest, Enum: OLLAMA
24.04.21 14:50:12: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 30051}
Invalid response from the model, trying again...
24.04.21 14:50:12: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 31767}
Model: llama3:latest, Enum: OLLAMA
24.04.21 14:50:19: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 31429}
Invalid response from the model, trying again...
24.04.21 14:50:19: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 33110}
Model: llama3:latest, Enum: OLLAMA
24.04.21 14:50:29: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 32886}
Invalid response from the model, trying again...
24.04.21 14:50:29: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 34510}
Model: llama3:latest, Enum: OLLAMA
24.04.21 14:50:37: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 34170}
Invalid response from the model, trying again...
24.04.21 14:50:37: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 35852}
Model: llama3:latest, Enum: OLLAMA

**Comment by xylozd** [comment]
> SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'write a Python game of "snake"', 'timestamp': '2024-04-19 16:48:23'}}```

something similar i got when i ran it last ,..

**Comment by mattietea** [comment]
I seem to be running into the same issue. I've tried `llama2:latest` and `llama3:70b`. I've tried restarting the client and server several times, removing `node_modules` and running `bun run start --host` (I saw someone mention this in another issue). Let me know if there's any other info that'd be helpful. Thanks.

<img width="600" alt="Screenshot 2024-04-22 at 20 12 33" src="https://github.com/stitionai/devika/assets/100300487/5f144add-55a7-47ad-9df5-bc8a555b2b02">


### Versions

```
macOS: 14.4
node: v21.7.3
bun: 1.1.4
```

### Ollama list (running on `127.0.0.1:11434`)

```
~ ollama list
NAME         	ID          	SIZE  	MODIFIED          
llama2:latest	78e26419b446	3.8 GB	5 hours ago      	
llama3:70b   	bcfb190ca3a7	39 GB 	About an hour ago	
llama3:latest	71a106a91016	4.7 GB	5 hours ago
```

### Server logs:

```logs
~ python devika.py 
...
Model: llama3:70b, Enum: OLLAMA
24.04.22 20:09:38: root: INFO   : /api/data GET
24.04.22 20:09:38: root: DEBUG  : /api/data GET - Response: {"models":{"CLAUDE":[["Claude 3 Opus","claude-3-opus-20240229"],["Claude 3 Sonnet","claude-3-sonnet-20240229"],["Claude 3 Haiku","claude-3-haiku-20240307"]],"GOOGLE":[["Gemini 1.0 Pro","gemini-pro"]],"GROQ":[["LLAMA3 8B","llama3-8b-8192"],["LLAMA3 70B","llama3-70b-8192"],["LLAMA2 70B","llama2-70b-4096"],["Mixtral","mixtral-8x7b-32768"],["GEMMA 7B","gemma-7b-it"]],"MISTRAL":[["Mistral 7b","open-mistral-7b"],["Mistral 8x7b","open-mixtral-8x7b"],["Mistral Medium","mistral-medium-latest"],["Mistral Small","mistral-small-latest"],["Mistral Large","mistral-large-latest"]],"OLLAMA":[["llama2","llama2:latest"],["llama3","llama3:70b"],["llama3","llama3:latest"]],"OPENAI":[["GPT-4 Turbo","gpt-4-turbo"],["GPT-3.5 Turbo","gpt-3.5-turbo-0125"]]},"projects":["Test"],"search_engines":["Bing","Google","DuckDuckGo"]}

24.04.22 20:09:38: root: INFO   : /api/get-agent-state POST
24.04.22 20:09:38: root: DEBUG  : /api/get-agent-state POST - Response: {"state":null}

Socket connected ::  {'data': 'frontend connected!'}
24.04.22 20:09:38: root: INFO   : SOCKET socket_response MESSAGE: {'data': 'Server Connected'}
24.04.22 20:09:40: root: INFO   : /api/get-agent-state POST
24.04.22 20:09:40: root: DEBUG  : /api/get-agent-state POST - Response: {"state":{"agent_is_active":true,"browser_session":{"screenshot":null,"url":null},"completed":false,"internal_monologue":null,"message":null,"step":null,"terminal_session":{"command":null,"output":null,"title":null},"timestamp":"2024-04-22 20:09:22","token_usage":365}}

24.04.22 20:10:02: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'Are you working?', 'timestamp': '2024-04-22 20:10:02'}}
```

**Comment by sritam2** [comment]
I also do have the same problem. Logs of devika (python devika.py):

> 24.04.24 02:24:16: root: INFO   : /api/get-agent-state POST
24.04.24 02:24:16: root: DEBUG  : /api/get-agent-state POST - Response: {
  "state": {
    "agent_is_active": true,
    "browser_session": {
      "screenshot": null,
      "url": null
    },
    "completed": false,
    "internal_monologue": null,
    "message": null,
    "step": null,
    "terminal_session": {
      "command": null,
      "output": null,
      "title": null
    },
    "timestamp": "2024-04-24 02:23:31",
    "token_usage": 363
  }
}

24.04.24 02:24:47: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'hello', 'timestamp': '2024-04-24 02:24:47'}}

The echo "Waiting....."
Waiting.....

How to resolve this? Should I roll back to some previous version?

**Comment by guidokruse** [comment]
I also do have the same problem. Logs of devika (python devika.py):

24.04.24 13:44:21: root: INFO   : Initializing Devika...
24.04.24 13:44:21: root: INFO   : Initializing Prerequisites Jobs...
24.04.24 13:45:32: root: INFO   : Loading sentence-transformer BERT models...
24.04.24 13:46:02: root: INFO   : BERT model loaded successfully.
24.04.24 13:46:35: root: INFO   : Ollama available
24.04.24 13:46:54: root: INFO   : Devika is up and running!

24.04.24 13:47:26: root: INFO   : /api/data GET
24.04.24 13:47:26: root: DEBUG  : /api/data GET - Response: {"models":{"CLAUDE":[["Claude 3 Opus","claude-3-opus-20240229"],["Claude 3 Sonnet","claude-3-sonnet-20240229"],["Claude 3 Haiku","claude-3-haiku-20240307"]],"GOOGLE":[["Gemini 1.0 Pro","gemini-pro"]],"GROQ":[["LLAMA3 8B","llama3-8b-8192"],["LLAMA3 70B","llama3-70b-8192"],["LLAMA2 70B","llama2-70b-4096"],["Mixtral","mixtral-8x7b-32768"],["GEMMA 7B","gemma-7b-it"]],"MISTRAL":[["Mistral 7b","open-mistral-7b"],["Mistral 8x7b","open-mixtral-8x7b"],["Mistral Medium","mistral-medium-latest"],["Mistral Small","mistral-small-latest"],["Mistral Large","mistral-large-latest"]],"OLLAMA":[["llama3","llama3:latest"]],"OPENAI":[["GPT-4 Turbo","gpt-4-turbo"],["GPT-3.5 Turbo","gpt-3.5-turbo-0125"]]},"projects":["test"],"search_engines":["Bing","Google","DuckDuckGo"]}

24.04.24 13:47:26: root: INFO   : /api/get-agent-state POST
24.04.24 13:47:26: root: DEBUG  : /api/get-agent-state POST - Response: {"state":null}

Socket connected ::  {'data': 'frontend connected!'}
24.04.24 13:47:26: root: INFO   : SOCKET socket_response MESSAGE: {'data': 'Server Connected'}
24.04.24 13:47:30: root: INFO   : /api/get-agent-state POST
24.04.24 13:47:30: root: DEBUG  : /api/get-agent-state POST - Response: {"state":{"agent_is_active":true,"browser_session":{"screenshot":null,"url":null},"completed":false,"internal_monologue":null,"message":null,"step":null,"terminal_session":{"command":null,"output":null,"title":null},"timestamp":"2024-04-23 20:20:48","token_usage":364}}

24.04.24 13:49:04: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'program a little snake game', 'timestamp': '2024-04-24 13:49:04'}}

terminal:
The echo "Waiting....."
Waiting.....

Can you please fix this issue since it prevents using devika. Thanks.

**Comment by guidokruse** [comment]
I tried but unfortunately it works not on Windows10

**Comment by ARajgor** [comment]
fixed. fetch the latest changes. for more read the changelog in discord.
